### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Intro Stage: Blue Shield enemy takes frontal damage. 

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#37]
![screenshot_2017-11-05-14-03-24](https://user-images.githubusercontent.com/33324878/32415588-52e8272e-c23c-11e7-8080-76f9effbc3e1.png)

**Comment by protoman** [comment]
Fixed in https://github.com/protoman/rockbot/commit/0501bc155c5ca0b46808589646592e735aa9e2d6

You don't need to open this kind of enemy-behavior problem for each stage, fix one, fix all :)

**Comment by ghost** [comment]
Guess again.  Still not fixed - tried after update in intro stage.
